# Generated by Django 4.2.16 on 2024-09-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firsts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='data',
            new_name='date',
        ),
    ]
