# Generated by Django 4.2.16 on 2024-09-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_image_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_address',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
